### ISSUE TITLE
attach additional storage during aegea launch

### ISSUE THREAD

**Issue by jamestwebber** [kislyuk/aegea#37]
Again, apologies if I don't see this in the options. I built AMIs without configuring additional storage but most users are going to need an additional volume to download and work with their data. When using `aegea batch` it is straightforward to request `/mnt=500` or something but I don't see a way to do this with `aegea launch`. This would be a useful feature, as the alternatives are

a) rebuild the images so they have storage volumes already (which requires assumptions about space requirements), or
b) have people launch instances from the console, although they'd have to format the volume themselves.

**Comment by kislyuk** [comment]
@jamestwebber - This is released in v2.1.0. The calling convention is the same as in `aegea batch`: `aegea launch  akislyuk-ebs-test4 --storage /foo=500 /bar=600`. Caveats:

- The volume type is hardcoded to be st1
- The filesystem type is hardcoded to be ext4
- Mountpoints must exist for mounts to succeed (although you can log in, mkdir the mounts (`mkdir /foo /bar` for the above example), and run `mount -a`, and the rest of it will work just fine).
- If you want the instance to automatically manage the filesystems for you, *you must rebuild the aegea base AMI* using `aegea build_ami NAME` for this to work. The change that I committed today reconfigures the base AMI to support auto-formatting, auto-mounting, and fstab enrollment of the filesystems. (You can log in to the instance and format and mount the filesystem manually using old/non-aegea AMIs.)

**Comment by jamestwebber** [comment]
Awesome, thanks!

So if I understand this correctly, I have to build the AMIs through aegea to use this capability? We had a plan to organize through Packer images but if we should reorient to build off of aegea we can do that. Or if there's a way to make sure our Packer-built AMIs are aegea-
compatible, that would be good too.

**Comment by kislyuk** [comment]
You could try, and as I described, you can use some of this capability with non-aegea AMIs. But I recommend using aegea to build the AMIs for now. I'm working with @ryanking to make the aegea and packer-based AMI build processes compatible.
