### ISSUE TITLE
Launch command stuck when launching instances in a private subnet

### ISSUE THREAD

**Issue by davidrissato** [kislyuk/aegea#55]
The instance is successfully launched, but the command never completes its execution:

```
$ aegea launch --subnet subnet-xxxx-xxxxx davidrc-dev-2

Identity added: /Users/david.rissatocruz/.ssh/aegea.launch.david.rissatocruz.xxxxxxx.pem (/Users/david.rissatocruz/.ssh/aegea.launch.david.rissatocruz.xxxxxxx.pem)
INFO:aegea:Launch spec user data is 1901 bytes long

(... command was stuck here ...)
```

It looks like this loop will never complete, because there is no `public_dns_name` in this case:
https://github.com/kislyuk/aegea/blob/49e0c7555c27645d2d810894ef4bd66ef3faab6e/aegea/launch.py#L210-L212

**Comment by kislyuk** [comment]
Fix released in v3.6.33, please try again.
